In [1]:
import importlib
import cricket_parser
importlib.reload(cricket_parser)
from cricket_parser import parse_match

import json
import pandas as pd
from pathlib import Path

data_dir = Path("data/raw/IPL Match Data")
match_files = list(data_dir.glob("*.json"))
print(f"Found {len(match_files)} match files")

Found 1243 match files

In [2]:
all_player_cards = []
errors = []

for i, filepath in enumerate(match_files):
    try:
        with open(filepath) as f:
            match = json.load(f)
        cards = parse_match(match, match_id=filepath.stem)
        all_player_cards.extend(cards)
    except Exception as e:
        errors.append({"file": filepath.name, "error": str(e)})

    if i % 100 == 0:
        print(f"Processed {i}/{len(match_files)} files...")

print(f"Done. Total player cards: {len(all_player_cards)}")
print(f"Errors: {len(errors)}")

Processed 0/1243 files...
Processed 100/1243 files...
Processed 200/1243 files...
Processed 300/1243 files...
Processed 400/1243 files...
Processed 500/1243 files...
Processed 600/1243 files...
Processed 700/1243 files...
Processed 800/1243 files...
Processed 900/1243 files...
Processed 1000/1243 files...
Processed 1100/1243 files...
Processed 1200/1243 files...
Done. Total player cards: 27909
Errors: 0

In [3]:
print(f"Match Files Found: {len(match_files)}")
print(f"Player Cards Found: {len(all_player_cards)}")
print(f"Average Players per match {len(all_player_cards)/len(match_files):.1f}")

Match Files Found: 1243
Player Cards Found: 27909
Average Players per match 22.5

In [4]:
df = pd.DataFrame(all_player_cards)
print(df.shape)
print("stumpings" in df.columns)

(27909, 26)
True

In [ ]:
print(df["team"].unique())

In [5]:
print(df["stumpings"].sum())
print(df[df["stumpings"] > 0][["player", "stumpings"]].groupby("player").sum().sort_values("stumpings", ascending=False).head(10))

387
              stumpings
player
MS Dhoni             47
KD Karthik           37
RV Uthappa           32
WP Saha              26
RR Pant              24
SV Samson            19
Q de Kock            17
AC Gilchrist         16
PA Patel             16
NV Ojha              10

In [ ]:
print(df.shape)
print(df.columns.to_list())
df.head()

In [ ]:
df.sort_values("total_fantasy_points", ascending= False).head(10)[["player", "team", "venue", "date", "runs", "wickets", "total_fantasy_points"]]

In [ ]:
df.groupby("team")["total_fantasy_points"].mean().sort_values(ascending=False)

In [ ]:
print(df["date"].min())
print(df["date"].max())
print(df["season"].unique())

In [ ]:
df["season"] = df["season"].astype(str)
df.groupby("season")["date"].nunique().sort_index()

In [8]:
import os
os.makedirs("data/processed", exist_ok= True)
df.to_csv("data/processed/player_match_features.csv", index = False)
print(f" saved {len(df)} rows to data/processed/player_match_features.csv")

 saved 27909 rows to data/processed/player_match_features.csv

In [9]:
pd.read_csv("data/processed/player_match_features.csv")

,match_id,player,team,opposition,venue,city,date,season,toss_winner,toss_decision,...,wickets,runs_conceded,balls_bowled,maidens,economy,total_wickets,player_innings,team_total,total_fantasy_points,stumpings
0,1426261,TM Head,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,0,0,0,0,0.00,6,1,182,31,0
1,1426261,Abhishek Sharma,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,0,0,0,0,0.00,6,1,182,26,0
2,1426261,AK Markram,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,0,0,0,0,0.00,6,1,182,4,0
3,1426261,Nithish Kumar Reddy,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,1,33,18,0,11.00,6,1,182,114,0
4,1426261,RA Tripathi,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,0,0,0,0,0.00,6,1,182,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27904,1473486,Suryansh Shedge,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,0,40,18,0,13.33,10,2,194,-7,0
27905,1473486,M Jansen,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,2,30,24,0,7.50,10,2,194,33,0
27906,1473486,Azmatullah Omarzai,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,1,39,24,0,9.75,10,0,194,10,0
27907,1473486,Harpreet Brar,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,1,21,12,0,10.50,10,0,194,10,0
27908,1473486,Arshdeep Singh,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,2,25,20,0,7.50,10,0,194,28,0

In [6]:
import os
os.makedirs("data/processed", exist_ok= True)
df.to_csv("data/processed/player_match_stats.csv", index = False)
print(f" saved {len(df)} rows to data/processed/player_match_stats.csv")

 saved 27909 rows to data/processed/player_match_stats.csv

In [7]:
pd.read_csv("data/processed/player_match_stats.csv")

,match_id,player,team,opposition,venue,city,date,season,toss_winner,toss_decision,...,wickets,runs_conceded,balls_bowled,maidens,economy,total_wickets,player_innings,team_total,total_fantasy_points,stumpings
0,1426261,TM Head,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,0,0,0,0,0.00,6,1,182,31,0
1,1426261,Abhishek Sharma,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,0,0,0,0,0.00,6,1,182,26,0
2,1426261,AK Markram,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,0,0,0,0,0.00,6,1,182,4,0
3,1426261,Nithish Kumar Reddy,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,1,33,18,0,11.00,6,1,182,114,0
4,1426261,RA Tripathi,Sunrisers Hyderabad,Punjab Kings,Maharaja Yadavindra Singh International Cricke...,Mohali,2024-04-09,2024,Punjab Kings,field,...,0,0,0,0,0.00,6,1,182,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27904,1473486,Suryansh Shedge,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,0,40,18,0,13.33,10,2,194,-7,0
27905,1473486,M Jansen,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,2,30,24,0,7.50,10,2,194,33,0
27906,1473486,Azmatullah Omarzai,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,1,39,24,0,9.75,10,0,194,10,0
27907,1473486,Harpreet Brar,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,1,21,12,0,10.50,10,0,194,10,0
27908,1473486,Arshdeep Singh,Punjab Kings,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,2025-04-30,2025,Punjab Kings,field,...,2,25,20,0,7.50,10,0,194,28,0

In [ ]:
df.columns.tolist()
print(df[["player", "team_total", "player_innings", "total_wickets"]].head(10))

In [ ]:
importlib.reload

In [ ]:
print(df[["player", "player_innings", "team_total", "total_wickets"]].head(10))
print(df["team_total"].describe())

In [ ]:
print("match_id" in df.columns)

In [ ]:
print(df["match_id"].nunique())